/*
# Add built-in flag and process category to risk rules

1. New Columns
- `risk_rules.is_builtin` (boolean, default false) — marks the 7 system-provided risk factors so they can't be deleted but can be edited.
- `risk_rules.process_category` (text, default 'moderate') — the Critical/High/Moderate/Low category assigned to alerts generated by this rule. Editable for both built-in and custom rules.

2. Seeded Data
- Inserts 7 built-in risk factor rows with is_builtin = true, each with a default process_category.
- These rows use rule_type values that the evaluation logic can reference: single_person_completion, time_limit, seal_matching, duplicate_seal, weight_reconciliation, process_deviation, manual_weight_no_photo.
- Uses ON CONFLICT DO NOTHING on a unique constraint (name, is_builtin) so re-running is safe.

3. Security
- No RLS changes — existing policies on risk_rules remain unchanged.
*/

ALTER TABLE risk_rules ADD COLUMN IF NOT EXISTS is_builtin boolean NOT NULL DEFAULT false;
ALTER TABLE risk_rules ADD COLUMN IF NOT EXISTS process_category text NOT NULL DEFAULT 'moderate';

INSERT INTO risk_rules (name, rule_type, severity_model, thresholds, scope, is_builtin, process_category)
VALUES
  ('Single-person completion', 'single_person_completion', 'pass_fail', '{}', 'process', true, 'high'),
  ('Time limit', 'time_limit', 'multi_level', '{"max_minutes": 60}', 'stage', true, 'moderate'),
  ('Seal matching', 'seal_matching', 'pass_fail', '{}', 'stage', true, 'critical'),
  ('Duplicate seal prevention', 'duplicate_seal', 'pass_fail', '{}', 'process', true, 'critical'),
  ('Weight reconciliation', 'weight_reconciliation', 'multi_level', '{"tolerance_kg": 0.5}', 'process', true, 'high'),
  ('Process deviation', 'process_deviation', 'pass_fail', '{}', 'stage', true, 'high'),
  ('Manual weight without photo', 'manual_weight_no_photo', 'pass_fail', '{}', 'stage', true, 'moderate')
ON CONFLICT DO NOTHING;
